#!/usr/bin/env bash
# performs 301 redirection

sudo apt update
sudo apt install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/mikoiyke permanent;"

sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

sudo service nginx restart
