#!/usr/bin/env bash
# Performs redirection
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s@listen 80 default_server;@$new_string@" /etc/nginx/sites-enabled/default
