#!/usr/bin/env bash
# performs 404 error code

sudo apt update
sudo apt install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/mikoiyke permanent;"

sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

#creates a 404 error page

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s@listen 80 default_server;@$new_string@" /etc/nginx/sites-enabled/default

#restarting the nginx service
sudo service nginx restart
