#!/usr/bin/env bash
# Configuration for HTTP response header

sudo apt update
sudo apt install -y nginx
sudo apt update

echo "Hello World!" | sudo tee /var/www/html/index.html


new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/mikoiyke permanent;"

sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

#creates a 404 error page

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sudo service nginx restart

sudo sed -i "/server_name_/a add_header x-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# test for syntax errors
sudo nginx -t

# restart nginx service
sudo service nginx restart
