#!/usr/bin/bash
# install the ufw firewall and setup a few rules

sudo apt update

sudo apt install ufw

sudo ufw allow 22

sudo ufw allow 443

sudo ufw allow 80

# To enable all new rules
sudo ufw enable
