#!/usr/bin/bash
# Update package lists
sudo apt update

# Install ufw if not already installed
sudo apt install ufw

# Allow SSH (port 22), HTTPS (port 443), and HTTP (port 80)
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80

# Deny all other incoming traffic
sudo ufw deny in

# Enable ufw
sudo ufw enable
