#!/usr/bin/bash
# Firewalls can not only filter requests, they can also forward them.
sudo apt update
sudo apt install iptables-persistent
sudo iptables-save | sudo tee /etc/iptables/rules.v4

sudo iptables -t nat -A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80

