#!/bin/env bash
# Short form of the code on task 1
sudo sed -i 's/user .*/user nginx/' /etc/nginx/nginx.conf
sudo sed -i 's/listen 80 default_server/listen 8080 default_server/' /etc/nginx/sites-available/default
sudo sed -i 's/listen \[::\]:80 default_server/listen [::]:8080 default_server/' /etc/nginx/sites-available/default
sudo systemctl restart nginx
